services:  
  - type: web
    name: customer-service
    env: python
    plan: free
    region: frankfurt
    buildCommand: "./build.sh"
    startCommand: "gunicorn cs_messaging.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cs_messaging.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: cs_messaging_db
          property: connectionString

databases:
  - name: cs_messaging_db
